twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/images/static': images
        '%kernel.project_dir%/public/images/web': photos
    globals:
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'
