vich_uploader:
    db_driver: orm

    mappings:
        lescityzens_photos:
            uri_prefix: /images/web
            upload_destination: '%kernel.project_dir%/public/images/web'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
