#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#captcha_routing : 
  #ressource :  "@ CaptchaBundle / Resources / config / routing.yml"

login:
    path:       /connexion
    controller: App\Controller\SecurityController::connexion
    methods: GET|POST
